pipeline {
    agent any 

    tools {
        maven 'mv' 
    }

    options {
        timeout(time: 1, unit: 'MINUTES') 
    }

    stages {
        stage('Build') {
            steps {
                
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
           
                sh 'mvn test'
            }
            post {
                always {
                    
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Publish Artifacts') {
            steps {
              
                archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: false
                echo "Artifacts published successfully."
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully!"
        }
        failure {
            echo "Pipeline failed."
        }
        always {
            cleanWs() 
        }
    }
}

