pipeline {
    agent any 
    environment {
        // Assuming the SSH private key is added to Jenkins Credentials as 'github-ssh-key'
        GIT_SSH_KEY = credentials('JENKINS-GITHUB-KEY')// Credential ID for the private key
    }
    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 'master', description: 'Enter the branch name to build')
    }

    tools {
        maven 'mv' 
    }

    options {
        timeout(time: 1, unit: 'MINUTES') 
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the branch using the parameter value
                
                sshagent(['JENKINS-GITHUB-KEY']) {
                    // Checkout the code from the GitHub repository using the SSH URL
                   git branch: "${params.BRANCH_NAME}", url: 'git@github.com:officialarun/Devops-Project.git'
                }
            }
        }
        stage('Build') {
            steps {
                
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
           
                sh 'mvn test'
            }
            post {
                always {
                    
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Publish Artifacts') {
            steps {
              
                archiveArtifacts artifacts: 'target/my-app-1.0-SNAPSHOT.jar', allowEmptyArchive: false
                echo "Artifacts published successfully."
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully!"
        }
        failure {
            echo "Pipeline failed."
        }
        
    }
}

